# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-24 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='工程师名字')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('work_years', models.IntegerField(default=0, verbose_name='工作年限')),
                ('work_position', models.CharField(max_length=50, verbose_name='公司职位')),
                ('expertise', models.CharField(max_length=50, verbose_name='专业特长')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
                ('image', models.ImageField(default='', upload_to='engineer/%Y/%m', verbose_name='头像')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': '工程师',
                'verbose_name_plural': '工程师',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='所在位置')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Team来自',
                'verbose_name_plural': 'Team来自',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='组名')),
                ('desc', models.TextField(verbose_name='组描述')),
                ('tag', models.CharField(default='专业测试', max_length=10, verbose_name='小组标签')),
                ('category', models.CharField(choices=[('develop', '研发'), ('test', '测试')], default='test', max_length=20, verbose_name='团队类型')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('image', models.ImageField(upload_to='team/%Y/%m', verbose_name='logo')),
                ('engineer_num', models.IntegerField(default=0, verbose_name='工程师人数')),
                ('equipment_num', models.IntegerField(default=0, verbose_name='设备数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.Location', verbose_name='所在位置')),
            ],
            options={
                'verbose_name': '组管理',
                'verbose_name_plural': '组管理',
            },
        ),
        migrations.AddField(
            model_name='engineer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Team', verbose_name='所属组'),
        ),
    ]
