# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-04-24 10:11
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=6, verbose_name='管理编号')),
                ('name', models.CharField(max_length=50, verbose_name='设备名称')),
                ('desc', models.CharField(max_length=300, verbose_name='设备描述')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='设备详情')),
                ('is_banner', models.BooleanField(default=False, verbose_name='是否轮播')),
                ('sn', models.CharField(max_length=50, verbose_name='设备序列号')),
                ('asset_num', models.CharField(max_length=15, verbose_name='设备资产编号')),
                ('type', models.CharField(max_length=20, verbose_name='设备型号')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('reserve_times', models.IntegerField(default=0, verbose_name='借用次数')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='设备标签')),
                ('has_checked_before_return', models.BooleanField(default=False, verbose_name='归还前是否查验')),
                ('reservable_inadvance', models.BooleanField(default=False, verbose_name='是否允许提前预定')),
                ('image', models.ImageField(upload_to='equipments/%Y/%m', verbose_name='封面图')),
                ('cal_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='校验日期')),
                ('next_cal_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='下次校验日期')),
                ('manufacturer', models.CharField(max_length=30, verbose_name='制造商')),
                ('location', models.CharField(max_length=30, verbose_name='设备位置')),
                ('status', models.CharField(choices=[('Inactive', '不在使用'), ('Active', '在用'), ('Maintenance', '保养中'), ('Calibration', '校验中')], max_length=20, verbose_name='设备状态')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Engineer', verbose_name='设备责任人')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Team', verbose_name='所属组')),
            ],
            options={
                'verbose_name': '所有设备',
                'verbose_name_plural': '所有设备',
            },
        ),
        migrations.CreateModel(
            name='EquipmentResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='资源名称')),
                ('download', models.FileField(upload_to='equipments/resource/%Y%m', verbose_name='资源文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.Equipment', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备资源',
                'verbose_name_plural': '设备资源',
            },
        ),
        migrations.CreateModel(
            name='EquipmentVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='视频名')),
                ('time', models.IntegerField(default=0, verbose_name='时长(分钟数)')),
                ('url', models.CharField(default='', max_length=200, verbose_name='访问地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.Equipment', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备视频',
                'verbose_name_plural': '设备视频',
            },
        ),
        migrations.CreateModel(
            name='BannerEquipment',
            fields=[
            ],
            options={
                'verbose_name': '轮播设备',
                'verbose_name_plural': '轮播设备',
                'proxy': True,
                'indexes': [],
            },
            bases=('equipments.equipment',),
        ),
        migrations.CreateModel(
            name='Plan2CaliEquipment',
            fields=[
            ],
            options={
                'verbose_name': '待校验设备',
                'verbose_name_plural': '待校验设备',
                'proxy': True,
                'indexes': [],
            },
            bases=('equipments.equipment',),
        ),
    ]
